### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by rauljmz** [JakobChristensen/Sitecore.Rocks#18]
Some of the labels don't match the terminology used in the documentation and training:

Design Layout -> Edit presentation details. The word Layout is used in most menus to mean presentation details.
Sublayouts been part of renderings in the add new menu. I would suggest renaming Renderings to Components, or Web Form Components.
Add Rendering -> Add Component

**Comment by JakobChristensen** [comment]
Hmm... Looking at the Sitecore UI, it looks like Layout, Renderings and Sublayouts are the predominate terms.

![image](https://cloud.githubusercontent.com/assets/2310296/15929976/a6544356-2e50-11e6-8a42-efd5cc243d4e.png)

"Controls" is also used in a couple of places.

It seems tricky to me to align with documentation/training when the UI is not aligned.

**Comment by rauljmz** [comment]
I think there is some sort of consistency. Sublayouts is ascx files only. Renderings include all the other types (controller renderings, view renderings, xslt, web controls, and the seldom used URL renderings itemrenderings, etc.). Both Sublayotus and Renderings are type of Controls (or also on occasion Components). My suggestion still stands, if you want instead of components use controls. 

Edit layout vs edit presentation details I think is a clear change. 
I would also add to the list xpath builder. I think everybody refers to it as Sitecore Query (not xpath, nor Sitecore xpath).

**Comment by nickwesselman** [comment]
Terminology seems consistent enough with current Sitecore practices.
