### ISSUE TITLE
Indexes

### ISSUE THREAD

**Issue by rauljmz** [JakobChristensen/Sitecore.Rocks#19]
Using the Tools -> Indexes option, only the "system" index is shown. It should show all the indexes defined in Sitecore.ContentSearch

**Comment by JakobChristensen** [comment]
Sitecore Rocks still only supports the old indexes - primarily due to backwards compatibility. Since Rocks 2.0 targets CMS 8.x and later, it should be easier to implement this.

Help wanted!

**Comment by JakobChristensen** [comment]
Updated to SC 8.2
