### ISSUE TITLE
Item not found error on Client/Applications in core

### ISSUE THREAD

**Issue by sobek85** [JakobChristensen/Sitecore.Rocks#20]
Using Sitecore Rocks 2.0.0.0 and latest Sitecore 8.2 build.

I'm getting a "The item was not found. It may have been deleted." error message when trying to expand "/sitecore/client/Applications" in the core database. I am able to double click and open the item however.

**Comment by JakobChristensen** [comment]
Odd - I can't reproduce it in CMS 8.1.160321.

I will see if I can get a hold of a CMS 8.2 build...

**Comment by sobek85** [comment]
I tried against 8.1 and couldn't reproduce either.

**Comment by sobek85** [comment]
Found out it works in rev. 60527 and broken in rev. 160603. If that helps

**Comment by JakobChristensen** [comment]
Hmm... I cannot reproduce it in CMS 8.2 rev 160603...

Seems to work fine.

**Comment by sobek85** [comment]
Hmm... That's strange. 

Leave it with me, ill try a fresh copy without any of the build scripts. The build scripts might be deserialising the item incorrectly

**Comment by sobek85** [comment]
Seems to work in the platform build but has the issue in a LegoLand build. Ill try and work out what has changed.
