### ISSUE TITLE
TDS-connection stopped working?

### ISSUE THREAD

**Issue by ullmark** [JakobChristensen/Sitecore.Rocks#24]
Hi, 
I've been using Sitecore Rocks and TDS in combination for a while and found it very useful to also have the plugin that created/modified in TDS while you were working in Rocks. 

I unknowingly had "automatic updates" on for Rocks which after an update caused all my settings changed in Rocks to revert back to default but also the TDS connection to stop working. I can't seem to find the plugin anymore using Sitecore->Manage Plugins...

I saw the notice about features being removed because of open sourcing it, is that one of them?

**Comment by JakobChristensen** [comment]
Hi Markus

You probably unintentionally upgraded to Rocks 2.0, which contains a lot of breaking changes - that is why the settings have been reset.

I don't think Hedgehog have updated their plugin to Rocks 2.0 - I will contact them.

**Comment by ullmark** [comment]
Yup, I have 2.0.0.33 now, I wasn't even aware I had auto-updates on in Visual Studio. I believe that is the default setting. 

Have to ask; Is it possible to install a specific version, and which is the latest stable in the 1-track?

**Comment by JakobChristensen** [comment]
You can get version 1.5.1.7 here:
http://vsplugins.sitecore.net/Older-Sitecore-Rocks-Versions.ashx

**Comment by ullmark** [comment]
Perfect! thank you very much!
