### ISSUE TITLE
VS 2015 Item Editor Label Font Color

### ISSUE THREAD

**Issue by MrSnappingTurtle** [JakobChristensen/Sitecore.Rocks#26]
Please look into the label colors in the dark skin for Visual Studio 2015. They are very dark and thus blend into the background. Thanks!

![labels](https://cloud.githubusercontent.com/assets/8148243/19051265/3649908a-8967-11e6-8a24-f1c86b8cb489.PNG)

**Comment by JakobChristensen** [comment]
Repeating the answer from community.sitecore.net:

Sitecore Rocks uses a mix of the system colors and Visual Studio colors.

The field label is a link and uses the system color for links.

There is no way to change the color in Rocks, but you can change the system color (probably not recommended).
