### ISSUE TITLE
GridDesigner launch button not displayed in properties field

### ISSUE THREAD

**Issue by MartinSvarrer** [JakobChristensen/Sitecore.Rocks#27]
I can not launch the GridDesigner from Rocks anymore.

Steps to reproduce:
1. Create a template
2. Setting a field as Single-Line Text
3. Set the Field Data Source to bindmode=server&editor=Sitecore.VisualStudio.UI.LayoutDesigners.Editors.GridDesigners.GridDesignerEditor,Sitecore.Rocks.GridDesigner 
4. Create view rendering and set template with GridDesigner field.
5. Go to layout, insert rendering.
6. Highlight rendering and view properties list

Expected result:
Properties field should show a button to launch GridDesigner

Actual result:
No button displayed in properties field, and cannot launch the GridDesigner.

**Comment by MartinSvarrer** [comment]
I am using VS2015 update 3 with Sitecore Rocks version 2.0.39.0

**Comment by JakobChristensen** [comment]
This is an issue in SPEAK as the editor string in the Grid renderings rendering parameters is not correct. Confirmed by Andrea.
