### ISSUE TITLE
Image selection not working in Visual Studio 2015 Professional Update 3

### ISSUE THREAD

**Issue by alexqfredrickson** [JakobChristensen/Sitecore.Rocks#29]
I created a content item with an empty Image field and attempted to assign an image to it using the "Browse for Image" option.  After a selection is made, the image path is not getting assigned to the content item, and the Image field is appearing as empty both before and after image selection.

This issue is happening in Visual Studio 2015 Professional Update 3 and Sitecore Rocks v.2.0.39.0.

**Comment by alexqfredrickson** [comment]
Hey Jakob, thanks for looking into this.  I can still reproduce the problem on my end - I'm on Windows 7 Professional and using Good Old Web Service with a Sitecore 7 instance.

I double-clicked a content item which contains an Image field and which is populated with an actual image from the media library folder.  Following this:

- On the Content screen, the '[Updating Image]' label appears between the image field name label and the image preview, even though I haven't attempted to update the image yet. The "Browse for Image" label no longer appears.
- When the image is clicked, the Browse dialog pops up, but after another image is selected, the image doesn't change and none of the item's image field raw values change (including the ```mediapath``` attribute).
 - Strangely, when values are entered into the ```Alt. Text``` or ```Width``` inputs, when the item is saved, these attributes are updated but the ```mediapath``` attribute is set to an empty string.

I can still change the value of the image field as-expected through the regular web-based Sitecore interface without issue.

**Comment by JakobChristensen** [comment]
I think this is due to using the Good Old Web Service which is not as capable as the Hard Rock Web Service.

Could you try to switch to the Hard Rock Web Service?

**Comment by alexqfredrickson** [comment]
That makes sense.  Unfortunately, I can't reproduce test this behavior using the Hard Rock Web Service as the issue cropped up on a client's machine who only uses Good Old Web Service.
