### ISSUE TITLE
Advanced publishing only publishing first of multiple items

### ISSUE THREAD

**Issue by lcjordan** [JakobChristensen/Sitecore.Rocks#30]
Selecting multiple items using a CTRL or Shift select and publishing using Tools -> Publishing -> Publish Item publishes all selected items.

However multiple items using a CTRL or Shift select and publishing using Tools -> Publishing -> Advanced Publishing only publishes the first item selected and not others that are added.

**Comment by JakobChristensen** [comment]
Fixed.
