### ISSUE TITLE
Attaching to the process w3wp.exe

### ISSUE THREAD

**Issue by AntonZelinsky** [JakobChristensen/Sitecore.Rocks#33]
Create the possibility in one click attaching to the process **w3wp.exe** in the extension Sitecore.Rocks for debug.

**Comment by JakobChristensen** [comment]
Hi Anton

This seems like a feature that is not specific to Sitecore Rocks.

Personally I use ReAttach:
https://marketplace.visualstudio.com/items?itemName=ErlandR.ReAttach
