### ISSUE TITLE
Duplicating sitecore item adds "- Copy" by default which is an invalid item name

### ISSUE THREAD

**Issue by AdhirRamjiawan** [JakobChristensen/Sitecore.Rocks#36]
Duplicating an item in the sitecore explorer adds "- Copy" to the new item name by default and is able to be created. However, when packaging these duplicated items and installing them on another sitecore instance, sitecore complains that the item name has invalid characters in them making the package somewhat useless:

![image](https://cloud.githubusercontent.com/assets/2063616/23293611/d58706ae-fa6f-11e6-9e46-df27e6415ea9.png)

**Comment by JakobChristensen** [comment]
Hi Adhir

I am guessing the dash (-) in the item name is what is causing the issue. Normally the dash is not an illegal character in an item name, but this is configurable, so I am also guessing that your target website has customized the valid item name regex.

Please confirm this.

**Comment by AdhirRamjiawan** [comment]
Hi Jakob,

That seems to be correct. I managed to find the config and tested it to now allow dashes. Is there no way for Sitecore rocks to validate against this config?

regards
Adhir

**Comment by JakobChristensen** [comment]
There is always a way :-)

Question is if we should go back to the original solution, which was to prefix the item name with "Copy of". In your example: "Copy of Style Finder".

This was changed to match the Visual Studio way of doing it, which is easier, since you just have to backspace to remove the added text.

**Comment by AdhirRamjiawan** [comment]
It makes sense to have it consistent with Visual Studio. 

Perhaps a warning dialog to indicate that the name might not be compatible with the Sitecore item name configured? The dialog could also have an option to not show again for the server you're connected too.

**Comment by nickwesselman** [comment]
Not a feature priority given that the name can be changed before duplicating, going to close for now.
