### ISSUE TITLE
removal of empty Placeholder/Rendering attributes

### ISSUE THREAD

**Issue by Yusuf-Capobianco** [JakobChristensen/Sitecore.Rocks#37]
discovered that there is a bug with Sitecore Rocks that is stripping out empty attributes (e.g. ph=””) that are required for sitecore templates.

Example:

Breaks :
`<r id="{672671F3-2295-4425-A85C-B7836EDB9B9D}" uid="{CFDF6610-BF91-4C7E-AC2C-0A8C4E762F62}" />`

Works :
`<r id="{672671F3-2295-4425-A85C-B7836EDB9B9D}" ph="" uid="{CFDF6610-BF91-4C7E-AC2C-0A8C4E762F62}" />`

Is there some kind of XML formatter that is doing the stripping?

**Comment by JakobChristensen** [comment]
Hi Yusuf

How does it break? As far as I know, the "ph" attribute is not required in layouts as renderings can be placed outside layouts.

Is it in combination with Layout Deltas?

**Comment by deeja** [comment]
I've replicated this 

- Install instance of Sitecore 8.2 160729 using SIM
- Add Hard Sitecore Rocks connection to site
- Remove placeholder key from Sample Rendering {493B3A83-0FA7-4484-8FC9-4680991CF743}
This stops the placeholder automatically being set when placed on the page.
- In Sitecore Rocks
-- Remove renderings from item (home)
-- Add Sample Rendering to item (home)
- In sitecore content editor
-- Presentation -> Details -> Final Layout -> Click Sample Layout or Edit

Error occurs `Exception Details: System.ArgumentNullException: Value cannot be null.`

**Fix**
Set placeholder via Sitecore Rocks

**Expected** 
The ability to set the placeholder via Sitecore

**Comment by JakobChristensen** [comment]
So this is (probably) Layout Deltas kicking in.

I have committed a fix that always writes the "ph" attribute to the layout Xml. As far as I can tell, it fixes the issue.
