### ISSUE TITLE
'Object reference not set to an instance' error

### ISSUE THREAD

**Issue by Balaji4Sitecore** [JakobChristensen/Sitecore.Rocks#38]
'Object reference not set to an instance' error while trying to create new connection & Test it.
I'm using VS 2013 & 2015 Professional + Sitecore Rocks 2.0 version.

i couldn't see any log entries & where can i find the log entries for this exception.

**NOTE:** i have recently migrated Sitecore Rocks version from 1.3 to 2.0

**Comment by JakobChristensen** [comment]
Hi Balaji

Could you provide a screenshot of the error? It sounds like a server error.

1) Did Rocks update the dll's on the server (Update Server Components)?
2) Can you enable Rocks logging - select main menu | Tools | Options | Sitecore | Options and check Is Logging Enabled. If you open the Output pane in VS, there should be a Sitecore entry. Now try again.

**Comment by Balaji4Sitecore** [comment]
thanks for your reply, i have attached images.1.Error message that triggered while connecting. 2. VS Output 

After some random attempts, i'm able to connect if i run fiddler side/side :( not sure whats happening.

![image](https://cloud.githubusercontent.com/assets/7302452/23540099/4f78fcf2-0005-11e7-9c70-474c8c615886.png)
![image](https://cloud.githubusercontent.com/assets/7302452/23540103/5af4302e-0005-11e7-9687-1547ec42accf.png)

**Comment by JakobChristensen** [comment]
Hmm... this is odd - I have no idea of why it works with fiddler. 

This is however clearly an exception that happens on the server, so it might be security or customizations of Sitecore.

1. There is nothing in the Sitecore logs?
2. Are you using Good Old Web Service or Hard Rock Web Version?
3. Which version of Sitecore are you using?
4. Are you using Http or Https?

**Comment by JakobChristensen** [comment]
Closing because of no reply.
