### ISSUE TITLE
Sitecore Rocks 'Speak Form Generator' Error

### ISSUE THREAD

**Issue by Balaji4Sitecore** [JakobChristensen/Sitecore.Rocks#40]
I'm seeing below error when i tried to create SPEAK form using SPEAK Form Generator

![image](https://cloud.githubusercontent.com/assets/7302452/23540202/e3516bb2-0005-11e7-90b9-4a8bc36beb32.png)

**Other Information:**

1.VS version: 2013/2015
2.Sitecore Rocks Version : 2.0.39.0
3.Sitecore.Rocks.Server*.dll doesnt have this Class ( decompliled through ILSPY)
4.Question was initially posted here : http://sitecore.stackexchange.com/questions/4686/sitecore-rocks-form-speak-form-generator-error

**Comment by JakobChristensen** [comment]
This functionality was removed in Rocks v2, but unfortunately this particular UI was left in. The reason is that SPEAK has changed a lot, and this particular was not widely used and out of date.

I have removed the dialog.

Sorry about this.
