### ISSUE TITLE
"The 'sitecorepackage' package did not load correctly" when opening Visual Studio.

### ISSUE THREAD

**Issue by cjaube** [JakobChristensen/Sitecore.Rocks#41]
I'm running Visual Studio 2013 (12.0.40629.00 Update 5) and after installing Sitecore Rocks ([Version 2.0.58](https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/2.0.58/artifacts)), I get the error, "The 'sitecorepackage' package did not load correctly" ever time I launch Visual Studio or try to interact with the Sitecore Rocks plugin. I download an older version of Sitecore Rocks ([Version 2.0.54](https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/2.0.54/artifacts)) and it started working correctly without error.

**Comment by JakobChristensen** [comment]
I think this is caused by the referenced Nuget packages. Rocks uses the official Nuget packages for Visual Studio, but they come in many versions. 

We have to figure out the right version of the Nuget packages for VS 2013, VS 2015 and VS 2017.

**Comment by JakobChristensen** [comment]
As far as I can see, Microsoft only supplies Nuget packages with VS assemblies for VS 2015 and later. There are no official packages for VS 2013 and earlier.

Previous versions of Rocks used unofficial packages by Sam Harwell (VSSDK.*).

I think Rocks should use the official packages, which unfortunately means, that official support for VS 2013 will have to be removed.

**Comment by eckmanca** [comment]
Confirmed same issue here, update 5 seems to be the cause.  I used the version @cjaube recommended (thanks!) and now can at least use Sitecore Rocks again until whenever company decides we can use VS 2015.

**Comment by jgoski** [comment]
Confirmed that this worked for me as well.  Nothing was responding on my Version 2.0.59 and I uninstalled and installed 2.0.54 instead.  Everything seems to be working great now.  Thank!!!

**Comment by JakobChristensen** [comment]
As commented above, Sitecore Rocks v2.1 no longer supports VS2013.

Last version to support VS 2013 is 2.0.59.

**Comment by victorantos** [comment]
@jgoski where can I find version 2.0.54? thanks!

**Comment by JakobChristensen** [comment]
On AppVeyor: https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/2.0.54/artifacts

**Comment by victorantos** [comment]
Thanks, it works now.
