### ISSUE TITLE
Adding New Connection with same Host Name fails silently

### ISSUE THREAD

**Issue by cjaube** [JakobChristensen/Sitecore.Rocks#42]
If I add a New Connection and use the same Host Name as I've used previously, but change something like the Data Provider, a new connection is not created and the old connection is not updated. It fails silently.

I did eventually find out (after a lot of frustration) that I could right click the connection and select Connections -> Modify Connection, and that worked as I'd expect. An error message from the New Connection dialog would have cleared this up really quick, rather than nothing, which made me erroneously think it had updated the connection successfully.

Sitecore Rocks, Version 2.0.54

**Comment by JakobChristensen** [comment]
This is a bug - should be fixed now - by delete the old connection before creating a new.
