### ISSUE TITLE
Can't upload media to newly created media folder

### ISSUE THREAD

**Issue by cjaube** [JakobChristensen/Sitecore.Rocks#43]
I created a "New Media Folder" and named it. Then I right clicked and selected "Upload Media" and selected an image. I received an "Item not found" exception stating that it could not find "New Folder". I was able to work around the issue by running a refresh on the Sitecore Explorer.

Sitecore Rocks, Version 2.0.54

**Comment by JakobChristensen** [comment]
This was caused by not updating the item path when renaming an item.

This is fixed now.
