### ISSUE TITLE
VS2017 - The Sitecore Template Wizard is not installed

### ISSUE THREAD

**Issue by chiragp** [JakobChristensen/Sitecore.Rocks#45]
After installed Sitecore Rocks on brand new VM with Visual Studio 2017, each time I open Visual Studio I am presented with the following error:

![sitecore-rocks-issue](https://cloud.githubusercontent.com/assets/5542585/25018063/d7249670-203a-11e7-9622-e4d188bfa05a.png)

I've also got Sitecore Rocks & VS2017 installed on my laptop but not seeing the same error.

**Comment by JakobChristensen** [comment]
The Sitecore Template Wizard is supposed to be installled when Rocks is installed into VS - unfortunately this feature in VS (not a Rocks feature) is pretty fragile. I suspect it is a security issue.

Rocks attempts to detect if the Sitecore.Template.Wizard.dll assembly is in the proper place when starting up to work around failed installations. If not, it will show this dialog.

Try clicking "Select where to install the Template Wizard" and copy the file to "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PublicAssemblies" (or something similar).

If this does not work, install the assembly in the GAC.

**Comment by zhangpeng-kooboo** [comment]
@JakobChristensen do you mean 'Sitecore.Rocks.TemplateWizard.dll' instead of 'Sitecore.Template.Wizard.dll'?

**Comment by rangler2** [comment]
I think so, that is what got installed for me, and I put it in here:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\PublicAssemblies

**Comment by JakobChristensen** [comment]
Yep - sorry - it is Sitecore.Rocks.TemplateWizard.dll

**Comment by zhangpeng-kooboo** [comment]
Yep - That is the only one I found :) thks for the great plugin.
