### ISSUE TITLE
Not able to open the solution in Visual Studio 2015

### ISSUE THREAD

**Issue by prajapati-jatin** [JakobChristensen/Sitecore.Rocks#47]
I forked the master branch and tried to open the solution in Visual Studio 2015. But the project Sitecore.Rocks.VisualStudio.csproj was denied to be opened.

Can anyone tell which version of VS I've to use for this?

**Comment by JakobChristensen** [comment]
Visual Studio 2017.

And you need the Visual Studio 2017 SDK installed as well.
