### ISSUE TITLE
Tristate error

### ISSUE THREAD

**Issue by lundebro** [JakobChristensen/Sitecore.Rocks#49]
Hi,
There is still an error with tristate fields in Sitecore Rocks. This was mentioned by Mikael in a post on this page: https://community.sitecore.net/developers/f/7/t/352 which you replied on, but from what I can tell this issue is still not fixed.

The GetValue method in TristateField.cs returns "-" (dash) for indeterminate values. When this value is stored on an item (for instance the "Open properties after add" property on a rendering), the Content Editor pops up a "Do you want to save the changes to the item" when navigating away from the item, even though no changes were made by the author.

**Comment by JakobChristensen** [comment]
Man, the code in the Content Editor is weird.

Indeterminate state is now and empty string.
