### ISSUE TITLE
Hard Rock Web Service has an unexpected version on remote instance

### ISSUE THREAD

**Issue by Epithach** [JakobChristensen/Sitecore.Rocks#50]
Hello,

My VS's Sitecore Rocks extension has updated on 2.1.69.0, but the version on my instance is 2.0.0.40 ! I can't updating it because the Sitecore Instance is on an another server, so I can't use the "Update Server Components" to do the update !
Do you have an advice for me ? Do you know if it is possible to dowload the necessary dll alone ?

Regards

**Comment by JakobChristensen** [comment]
Hi

Find your Sitecore Rocks installation directory - you can do this from the Sitecore Start Page | Sitecore Rocks | Open Sitecore Rocks application folder in Windows Explorer.

You need to copy Sitecore.Rocks.Server.dll to the /bin folder and the files in webservice directory to /sitecore/shell/webservice.

**Comment by Epithach** [comment]
Dll found, thanks !

**Comment by JakobChristensen** [comment]
Great.
