### ISSUE TITLE
Sitecore Rocks 2.1.69 - Gui error - Does not have a resource identified by the URI

### ISSUE THREAD

**Issue by kunukn** [JakobChristensen/Sitecore.Rocks#51]
![sitecore rocks 2 1 69](https://cloud.githubusercontent.com/assets/3199603/26683245/794a8008-46e3-11e7-93d6-0897caf077eb.PNG)

I am the only one getting this? happened from auto update to version 2.1.69

**Comment by kunukn** [comment]
A custom plugin inside the Plugins folder was the issue, after deleted it, it worked.
`\AppData\Local\Sitecore\Sitecore.Rocks.VisualStudio\Plugins\<A Custom Plugin>`

**Comment by JakobChristensen** [comment]
Great.
