### ISSUE TITLE
Rocks destroys rules field

### ISSUE THREAD

**Issue by mikaelnet** [JakobChristensen/Sitecore.Rocks#52]
Hi,

I've found that Rocks stores "ShortId" in the uid attributes in Rules fields. However, the Sitecore editor expects these to be regular ID's. This causes rules to be non-editable in the Sitecore Content Editor if there are more than one rule with a short uid. 

Here's how to reproduce this error:

- from a clean instance, open an existing item with a rules field using Rocks
- add two new rules and save the item
- open the rule editor in content editor
- notice that all rules cannot be selected
- open a browser inspector tool and notice uid field couldn't be parsed, so the div id's are rule_00000000000000000000000000000000

I reviewed RuleModel.cs and it seems like .ToShortId() is mostly used for uid, but at some locations the correct .ToString("B").ToUpperInvariant() construction is used. Not sure if this can be simply replaced everywhere or how many other this this may affect.

// Mikael

**Comment by JakobChristensen** [comment]
Hi Mikael

Thanks for a very good bug report!

This was a bit tricky to reproduce, but I think I found it.

In Rocks, Rules fields are now properly initialized with "uid" attribute in the "rule" tag. When adding a new Rule, Rocks now formats the "uid" of the "rule" tag properly.

"uid" attributes on "conditions", "actions", "condition" and "action" tags still use the ShortId formatting.
