### ISSUE TITLE
Queries: Problem with digits in node name?

### ISSUE THREAD

**Issue by mezmo** [JakobChristensen/Sitecore.Rocks#53]
I'll start this out with saying that I'm not sure if the problem is with Sitecore Rocks itself, or if Sitecore Queries are just broken. Basically I have a node structure of Sitecore content that is like so:
/sitecore/content/home/global/healthcare docs/000newitems. If I query to the "healthcare docs" level, it returns everything fine. So /sitecore/content/home/global/healthcare docs/* returns just what I'd expect. Going one step further, adding 000newitems to the path I get nothing, even though I have over a thousand items in there. Changing the name, dropping the digits to just "newitems", everything works fine, it's only with the leading digits that there's a problem, but I'm not allowed to rename it in any environment other than my dev instance.

**Comment by JakobChristensen** [comment]
Hi Mezmo

Sounds like a got-cha in Sitecore Query.

Have you tried escaping 000newsitems with # like this:

/sitecore/content/home/global/healthcare docs/#000newitems#

This makes Sitecore Query parse the zeros as a string.

**Comment by mezmo** [comment]
Sweet, thanks!
