### ISSUE TITLE
Rocks to TDS plugin no longer working

### ISSUE THREAD

**Issue by lundebro** [JakobChristensen/Sitecore.Rocks#54]
Hi,
Not sure if this is the right place to report this, but for the past couple of weeks/month or so, the TDS to Rocks connector doesn't seem to work properly on my machine. I no longer get the "Add to TDS project" options in the right-click menu in Sitecore Explorer, and when updating an existing TDS-managed item in Rocks, the .item file no longer gets automatically updated.

This is using VS 2017 (v15.2, 26430.14), Sitecore Rocks 2.1.69.0 and TDS 2 Rocks Connector 5.6.0.15

Have tried un/reinstalling both Rocks and the plugin to no avail.

Any ideas?

**Comment by JakobChristensen** [comment]
Hi

As far as I know, Hedgehog updated the Rocks to TDS plugin a couple of weeks ago, but I don't know if they had uploaded it yet. I will contact them.

**Comment by SaintSkeeta** [comment]
I just check locally with the same versions of everything above (VS 2017 (v15.2, 26430.14), Sitecore Rocks 2.1.69.0 and TDS 2 Rocks Connector 5.6.0.15) and it worked fine.
The connector v5.6.0.15 is the version with the fix, so this setup should be fine. Are there definitely no other versions of the connector installed, or TDS for that fact, on the machine?
As long as the connection URL and Website Folder match on both the Rocks connection and the TDS property page, the connector should work. Maybe open an item in Rocks first, then Sync and item in TDS next (from the project)....and then retry the context menu?
Also try double-clicking a TDS item to see if it opens in Rocks.

Let me know if that works.

**Comment by lundebro** [comment]
Hi,

I managed to get it working by uninstalling the Rocks Connector plugin, quitting VS, opening VS and installing 5.6.0.15 again. I must have been impatient before and just uninstalled/installed the plugin without restarting VS inbetween. Thanks for your quick responses.

**Comment by JakobChristensen** [comment]
Great
