### ISSUE TITLE
Publishing restrictions dates move fields from they were originally input

### ISSUE THREAD

**Issue by testpattern** [JakobChristensen/Sitecore.Rocks#58]
I set the Publishing Restrictions, Item, Publishable From and To dates and press OK. Next time I open the Publishing Restrictions, Item, I see the dates have moved. It looks like the 'from' field will always get the date in the past and the 'to' field will always get the date in the future. I would expect it to use whatever dates were put in the fields.

![sc-rocks-publish](https://user-images.githubusercontent.com/1181413/29315753-c325d826-81bc-11e7-9acf-f8ae77c2b82b.gif)

**Comment by JakobChristensen** [comment]
Gah - two fields were flipped.

Fixed.
