### ISSUE TITLE
Installing in VS 2017 15.3.2 results in VS crashing

### ISSUE THREAD

**Issue by ravensorb** [JakobChristensen/Sitecore.Rocks#61]
It looks like the latest version of VS 2017 and the currently published version of Sitecore Rocks are not compatible.  Installing the ad-in via the Extension Manager results in Visual Studio crashing hard when opening any solution (even non "sitecore" projects).

**Comment by JakobChristensen** [comment]
Hi Ravensorb

Sorry, I cannot reproduce this.

I am running VS Professional 15.3.2 and Sitecore Rocks 2.1.69 (installed from Extensions and Updates) without any issues.
