### ISSUE TITLE
Sitecore Explorer - Pressing shift + f10 issue

### ISSUE THREAD

**Issue by Simon-Gaudiuso** [JakobChristensen/Sitecore.Rocks#63]
“shift + f10” doesn't works properly  on the tree-view in Sitecore explorer. 

Selecting template from (master/Sitecore/template) and then Pressing shift + f10  displays a context menu with “Commandy” and “Refresh Gutter”. Whereas right clicking with a mouse display a totally different menu, where you have the option to create a new template, folder, etc.
This is an issue for blind user using a screenreader. 
Really would  appreciate if someone would look into this issue.
I’m using Jaws 2018 (Jaws is a screenreader)
Visual Studio 2015/2017 
Latest version of Sitecore Rocks.
Windows 7 os.

Thanks!

-Simon

**Comment by JakobChristensen** [comment]
Hi Simon

Should be fixed now. You can get the build here: https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/artifacts

**Comment by Simon-Gaudiuso** [comment]
Hi Jakob,

Thank you so much Jakob, it works like a charm!!!
I very much appreciate it, thank you.

Regards,

-Simon
