### ISSUE TITLE
Sitecore Option is disabled in context menu for Folder Sync 

### ISSUE THREAD

**Issue by amitabhvyas** [JakobChristensen/Sitecore.Rocks#64]
I am not able to use the folder Sync Functionality because when I right click on a folder in my Visual Studio solution the "Sitecore" Option is disable for me. I am using VS 2013 and Rocks 2.0.54.0.

**Comment by JakobChristensen** [comment]
Have you connected your project with a Sitecore website?

Right-click the project in the Solution Explorer and choose Sitecore | Project Properties. Then create or pick a connection.

**Comment by JakobChristensen** [comment]
Closed.
