### ISSUE TITLE
Commandy not responsing to Ctrl+Shift+Space

### ISSUE THREAD

**Issue by marnixdevrije** [JakobChristensen/Sitecore.Rocks#65]
Commandy window doesn't respond to key combination Ctrl+Shift+Space

Environment:
Sitecore 8.1.0 rev 160519
Visual Studio Enterprise 2017 (15.5.0)
ReSharper Ultimate 2017.2.2

**Comment by JakobChristensen** [comment]
I cannot reproduce this - Commandy works fine on my machine.

- Make sure you have focus in a Sitecore window (Sitecore Explorer, Content Editor etc).
- Ctrl+Shift+Space should work with both Resharper keyboard layouts (Standard and IntelliJ)
- Make sure Ctrl+Shift+Space is not hijacked by another plugin or VS itself.
- Try mapping Commandy to another shortcut - open main menu | Tools | Options | Sitecore | Keyboard Scheme  and filter by Commandy.

**Comment by marnixdevrije** [comment]
I have disabled and re-enabled ReSharper a few times. Did a few restarts of my laptop as well. Just after a certain amount of time Commandy all of a sudden worked again! :-)

I have no explanation for how this issue got resolved, but this issue can be closed :-)

**Comment by JakobChristensen** [comment]
Great, thanks!

**Comment by marnixdevrije** [comment]
As it turned out: i was running Microsoft Teams and it somehow 'hijacks' the key combination. When i stopped Microsoft Teams the key combination Ctrl+Shift+Space for Commandy started working again

**Comment by JakobChristensen** [comment]
OK - that explains it - lots of extensions fight for keyboard combinations :-)
