### ISSUE TITLE
Deleting Item in Sitecore 9 Throws Exception

### ISSUE THREAD

**Issue by robertmcrouch** [JakobChristensen/Sitecore.Rocks#66]
Deleting any item in Sitecore 9 initial release throws an exception.

![image](https://user-images.githubusercontent.com/6921969/33782019-852cf058-dc1c-11e7-8c42-d076ffeea72f.png)

**Comment by JakobChristensen** [comment]
Try the latest build from here: 
https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/artifacts

**Comment by robertmcrouch** [comment]
Worked perfectly, thanks for the fast response.
