### ISSUE TITLE
Sitecore package support

### ISSUE THREAD

**Issue by mikaelnet** [JakobChristensen/Sitecore.Rocks#67]
Hi,
The current package generator in Rocks uses a very similar xml format of the .package files as the built-in Sitecore Package Designer. Do you plan to support multiple sources, the ability to set item mode and merge mode and installation post steps? It's really convenient to be able to create module packages from within Visual Studio and it's easy to have .package files under version control, though only a few of our modules can be created this way due to this limitation.

**Comment by JakobChristensen** [comment]
Sorry, no, there are no plans to support sources, item modes, merge modes or post steps.

(Unless somebody makes a pull request.)

**Comment by JakobChristensen** [comment]
Closed.
