### ISSUE TITLE
Rocks cannot connect to sitecore 9.0

### ISSUE THREAD

**Issue by IvanSheyenko** [JakobChristensen/Sitecore.Rocks#68]
Try to connect rocks to sitecore 9. The following message is shown:
https://www.screencast.com/t/eG1ysLUbR

A solution found by the community:
http://www.rockpapersitecore.com/2017/10/sitecore-rocks-with-sitecore-9/

**Comment by kaalen** [comment]
You will encounter a couple of other issues once you apply the solution from Rock Paper. For example, deleting items doesn't work and I have not found a solution yet.

**Comment by JakobChristensen** [comment]
@IvanSheyenko: The connection is caused by the tightened security in SC9 when using SIF to install. It would be inappropriate for Rocks to try to overwrite these security settings. 

@kaalen: Some of these issues should be solved in version 2.1.86.
