### ISSUE TITLE
Failed to load image on Sitecore 9

### ISSUE THREAD

**Issue by andrewvieau** [JakobChristensen/Sitecore.Rocks#69]
![rocks-no-image](https://user-images.githubusercontent.com/2454839/35713141-619ded14-078b-11e8-84fb-4d3e188ae8ad.jpg)

I am unable to view images in the media library or added to image fields. I get a red X and a notice: Failed to load image: No imaging component suitable to complete this operation was found.

What's interesting is that this only happens on instances that have been installed using the Sitecore Install Framework.  On Sitecore 9 instances that I've installed using SIM, I can view images just fine in Rocks.

**Comment by JakobChristensen** [comment]
When SIF is used to install Sitecore 9, security is tightened. I am pretty sure this is a security issue.

I think it would be inappropriate for Rocks to try to lower the Sitecore security. 

Instead I have changed the error message.
