### ISSUE TITLE
Keep getting the "Could not establish trust relationship for the SSL/TLS secure channel with authority 'localhost'

### ISSUE THREAD

**Issue by JakobChristensen** [JakobChristensen/Sitecore.Rocks#7]
Love the idea of Sitecore Rocks but cant seem to connect to local instance. Keep getting the "Could not establish trust relationship for the SSL/TLS secure channel with authority 'localhost'. Remote certificate invalid..."
Here's my setup..
1. local sitecore instance setup in local IIS using :80 & :443. 443 Uses self-signed cert.
2. Content is displayed by just going to http://localhost. Stage is displayed by going to https://localhost/sitecore/login.
3. DB's are remote.

Connection-
Data provider: Hard Rock Web Service
Host name: localhost OR https://localhost
User name: smu\XXXXXXXX
Password: XXXXX
Location: C:\localdev\sitecore\Website

Any ideas why I cant connect? Is a self-signed cert not enough to authorize connection?

**Comment by BrentWhiteman** [comment]
A self-signed certificate can normally be used as long as it meets certain criteria.  Signed for the correct domain, and if necessary included as a 'Trusted Root' certificate.

I created mine using SelfSSL as I wanted a separate cert for a specific local site, e.g. xyz.com (set in the hosts file), and this works fine after following the above steps.

**Comment by nickwesselman** [comment]
Being tracked under #44
