### ISSUE TITLE
Error using the Clipboard Context menu - "Oh, come on, clipboard"

### ISSUE THREAD

**Issue by deeja** [JakobChristensen/Sitecore.Rocks#70]
![image](https://user-images.githubusercontent.com/174247/35744600-aacfd422-0838-11e8-8aae-b057dd92ea29.png)

New install of Sitecore Rocks v2.1.86.0 on new install of Visual Studio 2017 v15.5.6

Using the right click context menu produces the exception above .

![image](https://user-images.githubusercontent.com/174247/35744871-60c68faa-0839-11e8-8e8b-b544b8dc2464.png)

**Comment by deeja** [comment]
Full error message 

> Oh, come on, Clipboard, why can't you be opened!
> Sorry about this, can you try again?

**Comment by JakobChristensen** [comment]
I cannot reproduce this issue - it works when I run VS as Administrator and as non-Administrator.

Try running VS as Administrator to see if it solves the issue,

**Comment by deeja** [comment]
Running as Administrator and still have the issue. I'm able to use copy/paste generally in other parts of visual studio

**Comment by JakobChristensen** [comment]
Hmm... looking at the code, this is a COM exception.

I will dig deeper.

**Comment by deeja** [comment]
I found it! There was a program called [Clipboard Compare](https://www.scootersoftware.com/v4help/index.html?bcclipmain.html) running on my system. Removed that and all good now.
