### ISSUE TITLE
Templates not displaying

### ISSUE THREAD

**Issue by edouardr** [JakobChristensen/Sitecore.Rocks#71]
# Issue
The template dialog does not list templates. Prompts an empty dialog.
![image](https://user-images.githubusercontent.com/1897774/36180058-f1615ecc-1172-11e8-8f80-c3643506f500.png)

All use to work as expected, not sure what happened, as I didn't updated VS or the plugin.

I have tried couple of times to delete the extension as well as the content in C:\Users\[user]\App_Data\Local\Sitecore\

After reinstalling, still the same issue.

# Use cases

- As a user I should be able to set the base templates for a particular template
- As a user I should be able to set the insert options on the Standard Values of a template

# Test Case

- Open Sitecore Explorer
- Open path: /master/sitecore/templates/path_to_template
- Right click on template item
- In context menu: Select Set Base templates
- New dialog is prompted with empty list

# Config

- Visual Studio 2017 professionnal
- Sitecore 9
- Sitecore Rocks 2.1.86
- Data Provider: Hard Rock Web Service
- In my web.config I have:
```
  <!-- Development mode for Sitecore Rocks requires this to be able to interact with the web service -->
  <location path="sitecore/shell/WebService" xdt:Transform="Insert">
    <system.web>
      <authorization>
        <allow users="?,*" />
      </authorization>
    </system.web>
  </location>
```

**Comment by edouardr** [comment]
I also tried to use the 'Change template' option. And this time I got an exception.

When looking at the logs I could see:

> 25112 2018:02:14 10:29:05 ERROR Application error.
> Exception: System.Web.HttpParseException
> Message: Could not create type 'Sitecore.Visual.Service2'.
> Source: System.Web
>    at System.Web.UI.SimpleWebHandlerParser.GetType(String typeName)
>    at System.Web.UI.SimpleWebHandlerParser.GetTypeToCache(Assembly builtAssembly)
>    at System.Web.Compilation.SimpleHandlerBuildProvider.GetGeneratedType(CompilerResults results)
>    at System.Web.Compilation.BuildProvider.CreateBuildResult(CompilerResults results)
>    at System.Web.Compilation.BuildProvider.GetBuildResult(CompilerResults results)
>    at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
>    at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
>    at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
>    at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
>    at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath)
>    at System.Web.UI.WebServiceParser.GetCompiledType(String inputFile, HttpContext context)
>    at System.Web.Services.Protocols.WebServiceHandlerFactory.GetCompiledType(String url, HttpContext context)
>    at System.Web.Services.Protocols.WebServiceHandlerFactory.GetHandler(HttpContext context, String verb, String url, String filePath)
>    at System.Web.Script.Services.ScriptHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)
>    at System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

I have checked and Server components are correctly installed. I can see Sitecore.Rocks.Server.dll being in the bin folder of the website.

**Comment by JakobChristensen** [comment]
Hi Edouardr

Thank you for a very detailed error report!

It looks like you tried everything I could think of, but the second post indicates that the Sitecore.Rocks.Server.dll is not being loaded by IIS. I don't really have another guess than a security issue. Make sure the assembly can by loaded - both from a file security perspective and a IIS perspective.

On the other hand it looks like the Content Tree is loaded, so Sitecore.Rocks.Server.dll should be loaded.

**Comment by nickwesselman** [comment]
Thanks for the update @edouardr. I'll close for now, please reopen if you see this again.
