### ISSUE TITLE
Error "No Service" 

### ISSUE THREAD

**Issue by maghcc** [JakobChristensen/Sitecore.Rocks#72]
I am using Sitecore Rocks 2.1.86 in Visual Studio 2017. The Sitecore software is 8.2 with Update 4.
I am trying to connect to my local website and I got an error message "No Service". 
My database is in the remote server. 
Any suggestions/help would be appreciated.

**Comment by JakobChristensen** [comment]
I don't know if Sitecore 8.2 Update 4 has security tightened. If so, try adding this to your web.config:

```
  <!-- Development mode for Sitecore Rocks requires this to be able to interact with the web service -->
  <location path="sitecore/shell/WebService" xdt:Transform="Insert">
    <system.web>
      <authorization>
        <allow users="?,*" />
      </authorization>
    </system.web>
  </location>

```

Otherwise check if you can make a request to /sitecore/shell/webservice/service2.asmx

**Comment by maghcc** [comment]
Awesome! After adding the code you provided, it is working now.
Thank you so much for the help.
Yes, I am able to access /sitecore/shell/webservice/service2.asmx all the time.

**Comment by JakobChristensen** [comment]
Great!

**Comment by olefritsch** [comment]
I am experiencing the same issue but running Sitecore 9.0. Tried using Visual Studio 2015 and 2017, as well as Rocks v2.1.107, 2.1.86 and 2.1.69. 

The code in the web.config doesn't help.

Sitecore.Rocks.Server is in the /bin folder and service2.asmx is in the /sitecore/shell/WebService folder and navigating to /sitecore/shell/WebService/service2.asmx works without a problem.

Any help would be greatly appreciated!
