### ISSUE TITLE
tools > browse > experience editor does not work for mvc layouts

### ISSUE THREAD

**Issue by IvanSheyenko** [JakobChristensen/Sitecore.Rocks#76]
1. in rocks navigate ti an item with mvc presentation
2. try to open experience editor (tools > browse > experience editor)

Result:
the following url is loaded:
/default.aspx?sc_itemid=%7bA0C9EFCF-1EC8-4641-8A2E-9B42CC8D1FF3%7d&sc_mode=edit

Page shows "Default page" text.

Expected result:
Page opened in experience editor.

**Comment by andrewvieau** [comment]
Maybe not an ideal solution but something that could get you by for the project: 

Delete the default.aspx file from the web root.

I've been doing this all year and haven't seen any negative side effects yet.

**Comment by nickwesselman** [comment]
Can you guys try the VSIX from this latest build and let me know if it solves the issue for you?

https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/builds/19888982/artifacts

**Comment by andrewvieau** [comment]
Latest build solved the issue for me.

**Comment by nickwesselman** [comment]
This is resolved in the 2.1.126 release.
