### ISSUE TITLE
Rocks thinks items have changed when they have not

### ISSUE THREAD

**Issue by andrewvieau** [JakobChristensen/Sitecore.Rocks#77]
This isn't happening consistently on every item in my site, but frequently I notice that if I open an item and immediately close, Visual Studio will prompt me to save even though I haven't made any changes.

I serialized the items to compare and there is no change being made.

**Comment by nickwesselman** [comment]
@andrewvieau hmm do you have any additional reproduction steps for this?

**Comment by andrewvieau** [comment]
No and I haven't seen it in a long time.  I think this one can be closed.
