### ISSUE TITLE
Query Analyzer Not Found

### ISSUE THREAD

**Issue by mcraig33** [JakobChristensen/Sitecore.Rocks#81]
I'm trying to use the Query Analyzer feature of Sitecore Rocks, but when I go to Sitecore Explorer -> Connections -> [my site] -> master db, right-click master -> tools; Query Analyzer is not a menu option.

I've verified all Sitecore Rocks features are enabled
I tried additional databases (core and web) with the same result

Sitecore 8.2
Visual Studio 2017 Enterprise, version 15.7.4
Sitecore Rocks, version 2.1.86

**Comment by nickwesselman** [comment]
@mcraig33 Please ensure you are using the Hard Rock service and not the Good Old service. Functionality is limited when using the Good Old service.
