### ISSUE TITLE
Invalid username and password with Sitecore 9.1

### ISSUE THREAD

**Issue by GenZodd** [JakobChristensen/Sitecore.Rocks#89]
After installing Sitecore 9.1 and trying to connect Sitecore Rocks to it I get an error saying "Invalid username or password". I can use the same username and password to login to the UI but no Rocks. I assume this is related to switch the identity server. 

![image](https://user-images.githubusercontent.com/5560567/50237758-84c26c00-0372-11e9-9a5d-cab357a431ac.png)

I have tried the default sitecore/admin and just admin.

**Comment by nickwesselman** [comment]
We did not see this in our testing with 9.1, and have not seen any other reports. Is this just a vanilla 9.1 install using SIF? Are you using the Hard Rocks service?

**Comment by GenZodd** [comment]
Sorry forgot I logged this, thanks for pinging me on it. It was an issue with our install and the issue as been resolved and was caused by something else. Closing this out.
